development:
  bucket: palabra-fiel-dev 
  access_key_id: AKIAIUJHZ2SOVH6P4G5A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
    
test:
  bucket: 
  access_key_id: 
  secret_access_key: 
  max_file_size: 10485760
  acl: public-read
  
production:
  bucket: palabra-fiel-pro
  access_key_id: AKIAIUJHZ2SOVH6P4G5A
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
